version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-annotation"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dw209sqz52pz"
s3_prefix = "sam-app-annotation"
region = "us-east-2"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
